name: Generate LeetCode Progress Graph

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib

      - name: Run Python script
        run: |
          python generate_leetcode_graph.py 

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'
          message: 'Update LeetCode progress graph'
          add: 'images/leetcode_progress.png'
